package com.dao.pojo;

public class Bm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm.id
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm.branch
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    private String branch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm.id
     *
     * @return the value of bm.id
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm.id
     *
     * @param id the value for bm.id
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm.branch
     *
     * @return the value of bm.branch
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm.branch
     *
     * @param branch the value for bm.branch
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }
}