package com.dao.mapper;

import com.dao.pojo.Bm;
import com.dao.pojo.BmExample;
import com.dao.pojo.Employee_and_BMs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    long countByExample(BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int deleteByExample(BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int insert(Bm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int insertSelective(Bm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    List<Bm> selectByExample(BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    Bm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") Bm record, @Param("example") BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int updateByExample(@Param("record") Bm record, @Param("example") BmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int updateByPrimaryKeySelective(Bm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm
     *
     * @mbg.generated Wed Feb 03 17:15:28 CST 2021
     */
    int updateByPrimaryKey(Bm record);


    List<Bm> select_BM();

    List<Employee_and_BMs> select_bmid(int bmid);

    int insert_bm (String bmname);



}